### ISSUE TITLE
paramiko error

### ISSUE THREAD

**Issue by s4ms0n** [ployground/bsdploy#112]
Exception in thread Thread-5 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/samson/MyRepos/GIT/bsdploy/eggs/paramiko-1.18.2-py2.7.egg/paramiko/transport.py", line 1803, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

**Comment by s4ms0n** [comment]
have not seen any effect of this error. getting it from time to time

**Comment by fschulze** [comment]
with ansible I saw something like this:
```
Unhandled exception in thread started by 
sys.excepthook is missing
lost sys.stderr
```
It's most likely something related to proxycommand for ssh in ploy/paramiko.

**Comment by s4ms0n** [comment]
where do i look for the config? i can not find anything paramiko specific in my config
