### ISSUE TITLE
execnet error when using ploy configure (examples from quickstart, webserver tutorials)

### ISSUE THREAD

**Issue by wolfgangpfnuer** [ployground/bsdploy#22]
the below output was reproducable on a setup where the tutorial was followed during the training at europython.

venv was installed with python -m virtualenv
bin/activate was called
ploy ssh webserver / demo_jail both work without a problem

pkg install nginx worked without a problem inside the jail, so internet connection is not the problem.

pip freeze
Fabric==1.9.0
Jinja2==2.7.3
MarkupSafe==0.23
PyYAML==3.11
ansible==1.6.6
bsdploy==1.0.0
ecdsa==0.11
execnet==1.2.0
lazy==1.2
paramiko==1.14.0
ploy==1.0.0
ploy-ansible==1.0.0
ploy-ezjail==1.0.0
ploy-fabric==1.0.0
ploy-virtualbox==1.0.0
pycrypto==2.6.1
wsgiref==0.1.2

(lala)Retina Wolfgang 2012:ploy-quickstart wpfnuer$ ploy configure webserver
INFO: Using playbook at '/Users/wpfnuer/lala/ploy-quickstart/jailhost-webserver.yml'.

PLAY [jailhost-webserver] *****************************************************

GATHERING FACTS ***************************************************************
Write failed: Broken pipe
fatal: [jailhost-webserver] => Traceback (most recent call last):
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/ansible/runner/**init**.py", line 536, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/ansible/runner/__init__.py", line 638, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/ansible/runner/__init__.py", line 832, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/ansible/runner/action_plugins/normal.py", line 57, in run
    return self.runner._execute_module(conn, tmp, module_name, module_args, inject=inject, complex_args=complex_args)
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/ansible/runner/__init__.py", line 419, in _execute_module
    tmp = self._make_tmp_path(conn)
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/ansible/runner/__init__.py", line 1046, in _make_tmp_path
    result = self._low_level_exec_command(conn, cmd, None, sudoable=False)
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/ansible/runner/__init__.py", line 974, in _low_level_exec_command
    in_data=in_data)
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/ploy_ansible/execnet_connection.py", line 90, in exec_command
    rc, stdout, stderr = self.rpc.exec_command(remote_cmd)
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/ploy_ansible/execnet_connection.py", line 17, in call
    self.channel.send((name, args, kw))
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/execnet/gateway_base.py", line 681, in send
    self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
  File "/Users/wpfnuer/lala/lib/python2.7/site-packages/execnet/gateway_base.py", line 950, in _send
    raise IOError("cannot send (already closed?)")
IOError: cannot send (already closed?)

TASK: [install nginx] *********************************************************
FATAL: no hosts matched or all hosts have already failed -- aborting

**Comment by tomster** [comment]
@wolfgangpfnuer are you still willing to give this another try with the currently released 2.0.0 version?

**Comment by tomster** [comment]
And dito for @fbarthez of course :-)

**Comment by fbarthez** [comment]
I've had a quick go, but I don't get very far. After `make clean && git pull && bin/develop up -v`, deleting all existing ploy-related VMs and starting with the quickstart guide from scratch:

    (bsdploy)[fabian@toubab ~/Documents/gitolite/bsdploy/ploy-quickstart] % ploy start ploy-demo
    INFO: Creating instance 'ploy-demo'
    ERROR: The host only interface 'vboxnet0' has an IP '192.168.22.1' that doesn't match the config '192.168.56.1'.

This may be a remnant from my earlier experiments? The corresponding configuration has vanished from the etc/ploy.conf file as per the quickstart guide.

This is still on OSX 10.9.5.

**Comment by fschulze** [comment]
@fbarthez if you don't need that specific IP (192.168.22.x) for your VirtualBox host only interface, then just change it to '192.168.56.1' and you should be able to continue.

**Comment by fbarthez** [comment]
I've tried to follow the quickstart tutorial, which in the current version does not contain any explicit IP configuration. I tried adding the following to /etc/ploy.conf but w/o effect:

    [vb-hostonlyif:vboxnet0]
    ip = 192.168.56.1

The virtualbox UI shows only a single network adaptor, which is configured for NAT.

**Comment by fschulze** [comment]
Try using the ``VBoxManage`` command:

``VBoxManage list hostonlyifs``
``VBoxManage hostonlyif remove vboxnet0``

Once the one with IP 192.168.22.x is removed, try ploy again. It should then create a new one with the correct IP.

**Comment by fbarthez** [comment]
Thanks, that did help! I ended up with the same "Write failed: Broken pipe" when running ploy configure demo_jail, but this time it helped to create a symlink for python27:

    ln -s /usr/local/bin/python2.7 /usr/local/bin/python27

**Comment by tomster** [comment]
@fbarthez i'm very curious, where ``/usr/local/bin/python27`` is coming from.

it certainly isn't part of bsdploy.

is there perhaps a typo in your following the quickstart or perhaps a global ansible configuration on your system?

**Comment by fbarthez** [comment]
Well, if I remove the link, I'm back to "Write failed: Broken pipe" on calling "ploy configure demo_jail". The [alternative path was suggested](https://github.com/ployground/bsdploy/issues/22#issuecomment-63214062) by @fschulze.

My global ansible config:

    (bsdploy)[fabian@toubab ~/Documents/gitolite/bsdploy/ploy-quickstart] % cat ~/.ansible.cfg
    [defaults]
    transport = smart
    
    [ssh_connection]
    pipelining = True

**Comment by tomster** [comment]
@fbarthez well, @fschulze only said he wasn't sure which spelling is the correct one and the correct one is definitely ``python2.7``.

i'm wondering who or what is actually requesting ``python2.7`` and thus failing w/o the symlink you mention.

have you tried grepping for``python2.7`` (you will get a lot of hits for the ``pkg`` name for python 2.7 but besides those, can you find anything inside your project folder or your ploy installation?

i'm really curious, what this is :)

**Comment by fbarthez** [comment]
python2.7 is the name of the executable getting installed, so I'm guessing you'd like to see references to python27:

    (bsdploy)[fabian@toubab ~/Documents/gitolite/bsdploy/ploy-quickstart] % ack python27
    (bsdploy)[fabian@toubab ~/Documents/gitolite/bsdploy/ploy-quickstart] % 

So no python27 in the quickstart config – which seems unsurprising given I'm lazy and have copied verbatim from the docs.

    (bsdploy)[fabian@toubab ~/Documents/gitolite/bsdploy] % ack python27
    bsdploy/bootstrap_utils.py
    445:        packages.update(['python27'])
    
    bsdploy/fabfile_daemonology.py
    44:    bu.install_pkg('/', chroot=False, packages=['python27'])
    
    bsdploy/fabfile_mfsbsd.py
    127:    bootstrap_packages = ['python27']
    
    bsdploy/startup-ansible-jail.sh
    7:pkg install python27
    
    bsdploy/tests/test_bootstrap_daemonology.py
    33:        ('pkg install python27', {'shell': False}, '')]
    
    bsdploy/tests/test_bootstrap_mfsbsd.py
    142:        ('chroot /mnt pkg install python27', {'shell': False}, ''),
    
    bsdploy/tests/test_bootstrap_utils.py
    232:        ('wget -c -O "%(tempdir)s/downloads/packages/freebsd:10:x86:64/latest/All/python27-2.7.6_4.txz" "http://pkg.freebsd.org/freebsd:10:x86:64/latest/All/python27-2.7.6_4.txz"' % format_info, {}, ''),
    
    docs/advanced/customizing-bootstrap.rst
    59:    pkg install python27
    
    docs/quickstart.rst
    101:    python27-2.7.9                 Interpreted object-oriented programming language
    154:    python27-2.7.9                 Interpreted object-oriented programming language
    
    docs/setup/provisioning-ec2.rst
    68:        firstboot_pkgs_list="python27"
    
    lib/python2.7/site-packages/setuptools/msvc9_support.py
    60:                    message + ' Get it from http://aka.ms/vcpython27'
    
    lib/python2.7/site-packages/setuptools/tests/test_msvc9compiler.py
    77:        directing the user to download vcpython27.
    89:                assert 'aka.ms/vcpython27' in str(exc)
    
    lib/python2.7/site-packages/zc/buildout/buildout.txt
    1204:python27
    
    lib/python2.7/site-packages/zc/buildout/configparser.test
    320:  [s2: any([python2, python3, python24 , python25 , python26 , python27 , python30 , python31 , python32 , python33 , python34 , python35 , python36]) ] 
    
    lib/python2.7/site-packages/zc.buildout-2.3.1-py2.7.egg-info/PKG-INFO
    1323:        python27
