### ISSUE TITLE
Following the Quickstart, I get a TypeError bootstrapping the Jailhost

### ISSUE THREAD

**Issue by Subito** [ployground/bsdploy#50]
After the `ploy start ploy-demo` I add the mentioned lines to the ploy.conf and run `ploy bootstrap`. It doesn't ask me for an SSH-Key, it just throws the following error:
```
The following files will be downloaded on the host during bootstrap:
http://pkg.freebsd.org/freebsd:10:x86:64/quarterly/Latest/pkg.txz -> /mnt/var/cache/pkg/All/pkg.txz


Found the following disk devices on the system:
    cd0 ada0

Found the following network interfaces, now is your chance to update your rc.conf accordingly!
    em0 em1
Traceback (most recent call last):
  File "bin/ploy", line 9, in <module>
    load_entry_point('ploy==1.0.2', 'console_scripts', 'ploy')()
  File "/Users/fh/src/ploy/lib/python2.7/site-packages/ploy/__init__.py", line 540, in ploy
    return ctrl(argv)
  File "/Users/fh/src/ploy/lib/python2.7/site-packages/ploy/__init__.py", line 532, in __call__
    args.func(sub_argv, args.func.__doc__)
  File "/Users/fh/src/ploy/lib/python2.7/site-packages/bsdploy/__init__.py", line 42, in __call__
    instance.do('bootstrap', **{'bootstrap-yes': args.yes})
  File "/Users/fh/src/ploy/lib/python2.7/site-packages/ploy_fabric/__init__.py", line 281, in do
    return tasks[task](*args, **kwargs)
  File "/Users/fh/src/ploy/lib/python2.7/site-packages/bsdploy/fabfile_mfsbsd.py", line 143, in bootstrap
    _bootstrap()
  File "/Users/fh/src/ploy/lib/python2.7/site-packages/bsdploy/fabfile_mfsbsd.py", line 68, in _bootstrap
    rc_conf = bu.bootstrap_files['rc.conf'].read(template_context)
  File "/Users/fh/src/ploy/lib/python2.7/site-packages/bsdploy/bootstrap_utils.py", line 79, in read
    result = self.template_from_file(dirname(self.local), self.local, context)
  File "/Users/fh/src/ploy/lib/python2.7/site-packages/lazy/lazy.py", line 28, in __get__
    value = self.__func(inst)
  File "/Users/fh/src/ploy/lib/python2.7/site-packages/bsdploy/bootstrap_utils.py", line 73, in template_from_file
    inject_ansible_paths()
  File "/Users/fh/src/ploy/lib/python2.7/site-packages/ploy_ansible/__init__.py", line 41, in inject_ansible_paths
    C.DEFAULT_MODULE_PATH = pathsep.join([pathsep.join(extra_library), C.DEFAULT_MODULE_PATH])
TypeError: sequence item 1: expected string, NoneType found
```

**Comment by Subito** [comment]
After putting `ansible==1.7.2` in the Makefile, everything works again. Thanks @fschulze
