### ISSUE TITLE
Allow multiple IP addresses per jail

### ISSUE THREAD

**Issue by dlangille** [ployground/bsdploy#68]
When creating a jail, we should be able to have multiple IP addresses.

**Comment by tomster** [comment]
@fschulze : FTR atm ``ploy_ezjail`` actually breaks, when jails with multiple IPs are present (i.e. if they were added manually).

it barfs at the output of ``ezjail-admin list``:

```
STA JID  IP              Hostname                       Root Directory
--- ---- --------------- ------------------------------ ------------------------
ZR  2    10.0.1.20       var           /usr/jails/bar
DS  N/A  10.0.1.21       foo                            /usr/jails/foo
    N/A  10.0.1.22
```

like so:

```
# ploy -c etc/fitze_vbox.conf start webserver
Traceback (most recent call last):
  File "/Users/tomster/Development/tools/bin/ploy", line 42, in <module>
    sys.exit(ploy.ploy())
  File "/Users/tomster/Development/bsdploy/src/ploy/ploy/__init__.py", line 557, in ploy
    return ctrl(argv)
  File "/Users/tomster/Development/bsdploy/src/ploy/ploy/__init__.py", line 549, in __call__
    args.func(sub_argv, args.func.__doc__)
  File "/Users/tomster/Development/bsdploy/src/ploy/ploy/__init__.py", line 284, in cmd_start
    result = instance.start(overrides)
  File "/Users/tomster/Development/bsdploy/src/ploy_ezjail/ploy_ezjail/__init__.py", line 120, in start
    jails = self.master.ezjail_admin('list')
  File "/Users/tomster/Development/bsdploy/src/ploy_ezjail/ploy_ezjail/__init__.py", line 451, in ezjail_admin
    jails[entry.pop('name')] = entry
KeyError: 'name'

```

**Comment by fschulze** [comment]
Thanks for the output dump, that will allow me to write a test and fix this.

So what about the syntax in ploy.conf?
I think we should just have a comma separated list for the ``ip`` option and use the first IP for ssh connections etc.

**Comment by Infiniverse** [comment]
Is this still an issue?

**Comment by fschulze** [comment]
Yes, I got no feedback on my last question and thus haven't implemented it yet.

**Comment by Infiniverse** [comment]
Happy to give some feedback myself on this issue, but I need to resolve how to bind to different interfaces first (other than lo1). (Raised an issue about this in the bsdploy-ezjail repo).
