### ISSUE TITLE
Unable to ploy start quickstart - error on defaultdisk

### ISSUE THREAD

**Issue by smiklosovic** [ployground/bsdploy#86]
I am  following the tutorial on RTD and there is this snippet I am supposed to put to etc/ploy.conf and do ploy start quickstart

```
[vb-instance:quickstart]
vm-nic2 = nat
vm-natpf2 = ssh,tcp,,44003,,22
storage =
    --medium vb-disk:defaultdisk
    --type dvddrive --medium http://mfsbsd.vx.sk/files/iso/10/amd64/mfsbsd-se-10.1-RELEASE-amd64.iso --medium_sha1 03af247c1058a78a251c46ad5a13dc7b84a7ee7d
```
But in my case it errors on this:

```
Traceback (most recent call last):
  File "/home/smikloso/devel/bsdploy/bsdploy/bin/ploy", line 9, in <module>
    load_entry_point('ploy==1.2.0', 'console_scripts', 'ploy')()
  File "/home/smikloso/devel/bsdploy/bsdploy/lib/python2.7/site-packages/ploy/__init__.py", line 557, in ploy
    return ctrl(argv)
  File "/home/smikloso/devel/bsdploy/bsdploy/lib/python2.7/site-packages/ploy/__init__.py", line 549, in __call__
    args.func(sub_argv, args.func.__doc__)
  File "/home/smikloso/devel/bsdploy/bsdploy/lib/python2.7/site-packages/ploy/__init__.py", line 284, in cmd_start
    result = instance.start(overrides)
  File "/home/smikloso/devel/bsdploy/bsdploy/lib/python2.7/site-packages/ploy_virtualbox/__init__.py", line 327, in start
    medium = self.master.disks[medium[8:]].filename(self)
  File "/home/smikloso/devel/bsdploy/bsdploy/lib/python2.7/site-packages/ploy_virtualbox/__init__.py", line 540, in __getitem__
    self._cache[key] = self.klass(key, self.config[key])
KeyError: 'defaultdisk'
```

Thoughts?

**Comment by smiklosovic** [comment]
My bad, I had to create that disk first, something like this:

```
[vb-disk:defaultdist]
size = 25600
```
